### ISSUE TITLE
感谢分享，想咨询一下变化检测算法思路

### ISSUE THREAD

**Issue by autumoon** [martin98-afk/remote_sensing_change_detection#1]
感谢分享源码，初步看了一下，应该是通过分割结果来确定变化区域，但是这种检测方法鲁棒性较差，问下博主是如何优化这个问题的？顺便问下，标注文件都得手动标注吗？是否有公开数据集可以使用的呢？

**Comment by autumoon** [comment]
正在尝试跑通你的源代码。。。

Traceback (most recent call last):
  File "D:\Projects\remote_sensing_change_detection\train_and_validate.py", line 5, in <module>
    from utils.pipeline import RSPipeline
  File "D:\Projects\remote_sensing_change_detection\utils\pipeline.py", line 18, in <module>
    from models.nested_unet import NestedUNet
ModuleNotFoundError: No module named 'models.nested_unet'
